# Site settings
title: 졍 위키
url: "https://jiy0ung.github.io"
baseurl: ""
description: >
    졍 위키

# My information
email: jiyounghaan@gmail.com
author: Jiyoung
profile:
twitter_username:
github_username: JIY0UNG
comment-support: giscus

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  data_repo: JIY0UNG/JIY0UNG.github.io
  data_repo_id: R_kgDOIx2s_Q
  data_category: General
  data_category_id: DIC_kwDOIx2s_c4CTmkN

# google_analytics:
#   ua: SAMPLE-VALUE
#   encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/jiy0ung/jiy0ung.github.io/blame/main/_wiki"
edit: "https://github.com/jiy0ung/jiy0ung.github.io/edit/main/_wiki"
issue: "https://github.com/jiy0ung/jiy0ung.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
